services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  redisinsight:
    container_name: redisinsight

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:26.3.2

volumes:
  postgres_eshopdb:
  redisinsight_data:  